#!/bin/bash -l
#PBS -l nodes=2:ppn=8,pmem=2gb,walltime=24:00:00
#PBS -N name
#PBS -m ae
#PBS -e stderr
#PBS -o stdout
###PBS -q devel

DATA=$PBS_O_WORKDIR
cd $DATA

cat $PBS_NODEFILE | uniq | tr '\\012' ' ' > tmp1
read -a NODE < tmp1
rm tmp1

inode=-1
ijob=0

for ((K=1;K<=8;K++)); do
    [ $((++ijob % 8)) -eq 1 ] && ((inode++))
    ssh ${NODE[inode]} $DATA/sub$K &
done

wait

exit 0
