#!/bin/bash -l

module load intel
module unload vmpi/pathscale
module load ompi/intel

cd /scratch2/maerzkek/MCCCS-PARALLEL-BOLTZ/TEST_SUITE/LONG/TEST6

mpirun -np 4 /scratch2/maerzkek/MCCCS-PARALLEL-BOLTZ/NVT-Gibbs  

exit 0
