#!/bin/bash -l
#PBS -l walltime=02:00:00,pmem=500mb,nodes=5:ppn=8
#PBS -m ae

cd /home/xe1/maerzkek/MCCCS-2010-PARALLEL/TEST_SUITE/LONG

# unload and load required modules
module load intel
module unload pathscale vmpi/pathscale vmpi/intel ompi/pathscale
module load ompi/intel

# write out the nodes allocated for further processing

cat $PBS_NODEFILE > NODES

# This script will submit the jobs
./runMPI

exit 0
