! ENSEMBLE.INC

      real(8)::vbox,wbox,vinterb,vtailb,vintrab,vvibb,vbendb
     &   ,vtgb, vextb, velectb,vflucqb,v3garob
!      real(8)::velectb_intra, velectb_inter
      common /vwbox/  vbox(nbxmax),wbox(nbxmax),vinterb(nbxmax)
     &   ,vtailb(nbxmax),vintrab(nbxmax),vvibb(nbxmax)
     &   ,vbendb(nbxmax),vtgb(nbxmax),vextb(nbxmax)
     &   ,velectb(nbxmax),vflucqb(nbxmax),v3garob(nbxmax)
!      common /vabox/ velectb_intra(nbxmax),velectb_inter(nbxmax)
