MODULE parser_pdb
! *****************************************************************************
!> \brief Handles PDB (Protein Data Bank) files
!> 
!> PDB Format Description Version 2.2 from http://www.rcsb.org
!> COLUMNS       DATA TYPE       FIELD         DEFINITION
!> 
!>  1 -  6       Record name     "ATOM  "
!>  7 - 11       Integer         serial        Atom serial number.
!> 13 - 16       Atom            name          Atom name.
!> 17            Character       altLoc        Alternate location indicator.
!> 18 - 20       Residue name    resName       Residue name.
!> 22            Character       chainID       Chain identifier.
!> 23 - 26       Integer         resSeq        Residue sequence number.
!> 27            AChar           iCode         Code for insertion of residues.
!> 31 - 38       Real(8.3)       x             Orthogonal coordinates for X in
!>                                             Angstroms.
!> 39 - 46       Real(8.3)       y             Orthogonal coordinates for Y in
!>                                             Angstroms.
!> 47 - 54       Real(8.3)       z             Orthogonal coordinates for Z in
!>                                             Angstroms.
!> 55 - 60       Real(6.2)       occupancy     Occupancy.
!> 61 - 66       Real(6.2)       tempFactor    Temperature factor.
!> 73 - 76       LString(4)      segID         Segment identifier, left-justified.
!> 77 - 78       LString(2)      element       Element symbol, right-justified.
!> 79 - 80       LString(2)      charge        Charge on the atom.
! *****************************************************************************
  use var_type,only:double_precision,default_string_length
  use util_files,only:get_iounit,readLine
  use sim_cell
  use sim_particle
  use sim_zeolite,only:ZeoliteUnitCellGridType,ZeoliteBeadType,setUpAtom,setUpCellStruct
  IMPLICIT NONE
  PRIVATE
  PUBLIC :: readPDB !,writePDB

CONTAINS

  SUBROUTINE readPDB(filePDB,zeo,lunitcell,lhere,ztype,zcell,zunit)
    character(LEN=*),intent(in)::filePDB
    type(MoleculeType),intent(out)::zeo
    logical,allocatable,intent(out)::lunitcell(:)
    logical,intent(out)::lhere(:)
    type(ZeoliteBeadType),intent(out)::ztype
    type(CellMaskType),intent(out)::zcell ! the "type" component of (Cell)zcell is the index in (ZeoliteBeadType)ztype
    type(ZeoliteUnitCellGridType),intent(out)::zunit

    INTEGER::IOPDB,jerr,i,resID
    CHARACTER(LEN=default_string_length)::line,atomName,resName,molName,elem
    logical::uninitialized
    real(KIND=double_precision)::occup,beta

    IOPDB=get_iounit()
    open(unit=IOPDB,access='sequential',action='read',file=filePDB,form='formatted',iostat=jerr,status='old')
    if (jerr.ne.0) then
       call cleanup('cannot open zeolite PDB file')
    end if
    
    CALL readLine(IOPDB,line,.false.,jerr)
    IF(jerr.ne.0) call cleanup('wrong PDB file format')

    read(line(2:),*) zeo%nbead,zunit%dup(1),zunit%dup(2),zunit%dup(3),ztype%ntype
    allocate(zeo%bead(zeo%nbead),lunitcell(zeo%nbead),ztype%name(ztype%ntype),ztype%radiisq(ztype%ntype),ztype%type(ztype%ntype),ztype%num(ztype%ntype),stat=jerr)
    if (jerr.ne.0) call cleanup('readPDB: allocation failed')

    do i=1,ztype%ntype
       CALL readLine(IOPDB,line,.false.,jerr)
       IF(jerr.ne.0) call cleanup('wrong PDB file format')
       read(line(2:),*) ztype%name(i),ztype%type(i),ztype%radiisq(i)
       lhere(ztype%type(i))=.true.
       ztype%radiisq(i)=ztype%radiisq(i)*ztype%radiisq(i)
       ztype%num(i)=0
    end do
    
    uninitialized=.true.
    i=0
    DO
       CALL readLine(IOPDB,line,.true.,jerr)
       IF(jerr.ne.0) EXIT

       SELECT CASE (line(1:6))
       CASE ("CRYST1")
          read(line(7:),*) zcell%boxl(1)%val,zcell%boxl(2)%val,zcell%boxl(3)%val,zcell%ang(1)%val,zcell%ang(2)%val,zcell%ang(3)%val
          call setUpCellStruct(zcell,zunit)
          uninitialized=.false.
       CASE ("ATOM","HETATM")
          if (uninitialized) call cleanup('PDB: CRYST1 needs to be defined before ATOM')
          i = i + 1
          READ(line(13:16),*) atomname
          READ(line(18:20),*,IOSTAT=jerr) resName
          READ(line(23:26),*,IOSTAT=jerr) resID
          READ(line(31:38),*,IOSTAT=jerr) zeo%bead(i)%coord(1)
          READ(line(39:46),*,IOSTAT=jerr) zeo%bead(i)%coord(2)
          READ(line(47:54),*,IOSTAT=jerr) zeo%bead(i)%coord(3)
          READ(line(55:60),*,IOSTAT=jerr) occup
          READ(line(61:66),*,IOSTAT=jerr) beta
          READ(line(73:76),*,IOSTAT=jerr) molName
          READ(line(77:78),*,IOSTAT=jerr) elem

          IF (LEN_TRIM(elem).eq.0) THEN
             ! Element is assigned on the basis of the atomName
             elem = atomname
          END IF
          IF (LEN_TRIM(molName).eq.0) THEN
             ! If molname is missing (as in the PDB generated by VMD) let's
             ! use the resname for the molname
             molName =  resname
          END IF

          call setUpAtom(elem,i,zeo,lunitcell,ztype,zcell,zunit)
       CASE ("END","TER")
          EXIT
       CASE ("REMARK")
       CASE DEFAULT
       END SELECT
    END DO

    if (i.ne.zeo%nbead) call cleanup('PDB: Number of atoms incorrect')
    
  END SUBROUTINE readPDB

! *****************************************************************************
!   SUBROUTINE writePDB ()
  
!     INTEGER, INTENT(IN)                      :: file_unit
!     TYPE(topology_parameters_type)           :: topology
!     TYPE(section_vals_type), POINTER         :: subsys_section
!     TYPE(cp_error_type), INTENT(inout)       :: error

!     CHARACTER(len=*), PARAMETER :: routineN = 'write_coordinate_pdb', &
!       routineP = moduleN//':'//routineN

!     CHARACTER(LEN=default_string_length)     :: line, my_tag1, my_tag2, &
!                                                 my_tag3, my_tag4, record
!     INTEGER                                  :: handle, i, id1, id2, idres, &
!                                                 iw, natom
!     LOGICAL                                  :: ldum
!     TYPE(atom_info_type), POINTER            :: atom_info
!     TYPE(cp_logger_type), POINTER            :: logger
!     TYPE(section_vals_type), POINTER         :: print_key

!     NULLIFY(logger)
!     logger => cp_error_get_logger(error)
!     iw = cp_print_key_unit_nr(logger,subsys_section,"PRINT%TOPOLOGY_INFO/PDB_INFO",&
!          extension=".subsysLog",error=error)    
!     print_key => section_vals_get_subs_vals(subsys_section,"TOPOLOGY%DUMP_PDB",error=error) 
!     CALL timeset(routineN,handle)

!     atom_info => topology%atom_info
!     record = cp_print_key_generate_filename(logger,print_key,&
!          extension=".pdb",my_local=.FALSE.,error=error)

!     IF(iw>0) WRITE(iw,*) "    Writing out PDB file ",TRIM(record)

!     natom = topology%natoms
!     idres = 0
!     id1   = 0
!     id2   = 0
!     DO i=1,natom

!        IF (topology%para_res) THEN
!           idres = atom_info%label_resid(i)
!        ELSE
!           IF((id1/=atom_info%map_mol_num(i)).OR.(id2/=atom_info%map_mol_typ(i))) THEN
!              idres = idres + 1
!              id1 = atom_info%map_mol_num(i)
!              id2 = atom_info%map_mol_typ(i)
!           END IF
!        END IF

!        line = ""
!        my_tag1 = atom_info%label_atmname(i); ldum=qmmm_ff_precond_only_qm(my_tag1)
!        my_tag2 = atom_info%label_resname(i); ldum=qmmm_ff_precond_only_qm(my_tag2)
!        my_tag3 = atom_info%label_molname(i); ldum=qmmm_ff_precond_only_qm(my_tag3)
!        my_tag4 = atom_info%element(i)      ; ldum=qmmm_ff_precond_only_qm(my_tag4)
!        WRITE(line(1 : 6),'(A6)')"ATOM  "
!        WRITE(line(7 :11),'(I5)')i
!        WRITE(line(13:16),'(A4)')ADJUSTL(my_tag1(1:4))
!        WRITE(line(18:20),'(A3)')TRIM(my_tag2)
!        WRITE(line(23:26),'(I4)')idres
!        WRITE(line(31:38),'(F8.3)')atom_info%r(1,i)*angstrom
!        WRITE(line(39:46),'(F8.3)')atom_info%r(2,i)*angstrom
!        WRITE(line(47:54),'(F8.3)')atom_info%r(3,i)*angstrom
!        IF (ASSOCIATED(atom_info%occup)) THEN
!           WRITE(line(55:60),'(F6.2)') atom_info%occup(i)
!        ELSE
!           WRITE(line(55:60),'(F6.2)') 0.0_dp
!        ENDIF
!        IF (ASSOCIATED(atom_info%beta)) THEN
!            WRITE(line(61:66),'(F6.2)') atom_info%beta(i)
!        ELSE
!            WRITE(line(61:66),'(F6.2)') 0.0_dp
!        ENDIF
!        WRITE(line(73:76),'(A4)')TRIM(my_tag3)
!        WRITE(line(77:78),'(A2)')TRIM(my_tag4)

!        WRITE(file_unit,"(A)")line
!     END DO
!     WRITE(file_unit,"(A3)")"END"

!     IF(iw>0) WRITE(iw,*) "  Exiting write_coordinate_pdb"

!     CALL cp_print_key_finished_output(iw,logger,subsys_section,&
!          "PRINT%TOPOLOGY_INFO/PDB_INFO",error=error)

!     CALL timestop(handle)

!   END SUBROUTINE writePDB

END MODULE parser_pdb
